### ISSUE TITLE
Sound Notification

### ISSUE THREAD

**Issue by Anshad007** [heytulsiprasad/alert-me-google-meet#2]
Hi there!. I myself was thinking of writing this extension for my personal use but i wanted to check if there was an already existing solution and i found yours. It's exactly what i wanted except one thing missing: There's no sound notification. I want it to alert me by making a sound.

**Comment by Anshad007** [comment]
> Hi there!. I myself was thinking of writing this extension for my personal use but i wanted to check if there was an already existing solution and i found yours. It's exactly what i wanted except one thing missing: There's no sound notification. I want it to alert me by making a sound.

Hi! Can i please implement this feature? I have never created a chrome extensions(probably because i never found the need), but i want to contribute this feature. So if you will be so humble as to let me implement it i would be delighted to study and work on this ASAP.

**Comment by heytulsiprasad** [comment]
Hi @Anshad007, appreciate your excitement really!

This was my first extension as well and I learnt a lot. However, it alerts in the default way common browsers notify (which also makes a beep sound), make sure you've allowed all access. 

If you meant something else though, feel free to @ me in this thread itself.

**Comment by heytulsiprasad** [comment]
Also, no need to ask for permission, feel free to share your ideas and start implementing any other feature you like, I'll happy discuss about it.

**Comment by Anshad007** [comment]
> Hi @Anshad007, appreciate your excitement really!
> 
> This was my first extension as well and I learnt a lot. However, it alerts in the default way common browsers notify (which also makes a beep sound), make sure you've allowed all access.
> 
> If you meant something else though, feel free to @ me in this thread itself.

Ah yes i use Debian 10 and it by default doesn't make sound or maybe uses different notification API, i am not sure hehe.
I'll try forking your code and modify so that it works for me.

Anyways you did a very good job for your first extension and it's a useful one too so congrats.
