### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by hirenchalodiya1** [heytulsiprasad/alert-me-google-meet#3]
getting this issue on first-time use
Also I can not find div with with property `jscontroller=D1tHje` on inspection
![image](https://user-images.githubusercontent.com/32496777/111136062-52c90000-85a3-11eb-963d-aeaca2db6907.png)

**Comment by heytulsiprasad** [comment]
Yeah this was possible, as at the time I made meet had its caption enclosed in a div with this attribute, it might not be the same now.

I'd have to inspect the div and pull out a new release. Thanks for letting me know. @hirenchalodiya1

**Comment by heytulsiprasad** [comment]
The new release v0.2.1-beta fixes this issue.

**Comment by ZokiDespotovski** [comment]
I got the same error. 
What I notice in the stacktrace and source code is that you search for `jscontroller=TEjq6e`
`const subtitleDiv = document.querySelector("div[jscontroller='TEjq6e']");`, while for my meeting in the html i see that jscontroller with that value does not exist.
